"""Pipeline DAG structure, validation, and execution planning.

Defines Pipeline class that composes stages into a directed acyclic graph,
validates inputs/outputs, detects circular dependencies, and generates
execution plans with scheduling constraints.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from kinetic_ai.pipeline.stage import MachineType, Stage


class PipelineError(Exception):
    """Base exception for pipeline validation failures."""

    pass


@dataclass
class ExecutionPlan:
    """Execution plan for a validated pipeline.

    Generated by Pipeline.validate_and_plan(), it carries:
    - Topological ordering of stages
    - Cost estimates
    - Machine assignments
    - Artifact producer tracking
    """

    stages: list[Stage] = field(default_factory=list)
    stage_order: list[str] = field(default_factory=list)
    total_cost_gpu_hours: float = 0.0
    machine_assignments: dict[str, MachineType] = field(default_factory=dict)
    artifact_producers: dict[str, str] = field(default_factory=dict)
    _stage_by_name: dict[str, Stage] = field(default_factory=dict, repr=False)

    def get_ready_stages(self) -> list[str]:
        """Return stages that can start immediately (have no input dependencies).

        At pipeline startup, only stages with no inputs can begin. As stages
        complete, new stages become ready when their inputs are produced.
        """
        ready = []
        for stage_name in self.stage_order:
            stage = self._stage_by_name[stage_name]
            if not stage.inputs:  # No dependencies = ready immediately
                ready.append(stage_name)
        return ready

    def get_artifact_producers(self) -> dict[str, str]:
        """Return mapping from artifact name to the stage that produces it."""
        return self.artifact_producers.copy()

    def detect_gpu_conflicts(self) -> list[tuple[str, str]]:
        """Detect GPU scheduling conflicts (informational only).

        Returns list of (stage1, stage2) pairs that are both GPU stages on the
        same machine type with no data dependency between them. These stages
        cannot run concurrently due to the global GPU lock constraint, but
        they can be executed sequentially in the order provided by stage_order.

        This is informational; it does not cause validation to fail, as the
        pipeline's topological order ensures schedulability.
        """
        conflicts = []

        # Find all GPU stages grouped by machine type
        gpu_by_machine: dict[MachineType, list[str]] = {}
        for stage_name, machine_type in self.machine_assignments.items():
            if machine_type in [MachineType.GPU_32GB, MachineType.GPU_120GB]:
                if machine_type not in gpu_by_machine:
                    gpu_by_machine[machine_type] = []
                gpu_by_machine[machine_type].append(stage_name)

        # For each machine type, check if multiple stages compete for the GPU
        for _machine_type, stages in gpu_by_machine.items():
            if len(stages) > 1:
                # Multiple stages on same GPU; check for data dependencies
                for i, s1_name in enumerate(stages):
                    for s2_name in stages[i + 1:]:
                        s1 = self._stage_by_name[s1_name]
                        s2 = self._stage_by_name[s2_name]
                        # Check if there's a data dependency between them
                        s1_produces_for_s2 = any(out in s2.inputs for out in s1.outputs)
                        s2_produces_for_s1 = any(out in s1.inputs for out in s2.outputs)
                        if not (s1_produces_for_s2 or s2_produces_for_s1):
                            # No data dependency: they'd need to serialize at runtime
                            conflicts.append((s1_name, s2_name))

        return conflicts


@dataclass
class Pipeline:
    """LLM construction pipeline: composable stages in a DAG.

    The pipeline collects stages, validates the DAG for:
    - Circular dependencies
    - Missing inputs (artifact not produced by any prior stage)
    - Duplicate outputs (two stages producing the same artifact)
    - GPU scheduling conflicts (two stages on same GPU concurrently)

    Then generates an ExecutionPlan with topological ordering.
    """

    name: str
    stages: dict[str, Stage] = field(default_factory=dict)

    def add_stage(self, stage: Stage) -> Pipeline:
        """Add a stage to the pipeline.

        Args:
            stage: Stage to add.

        Returns:
            Self for method chaining.

        Raises:
            PipelineError: If stage name already exists.
        """
        if stage.name in self.stages:
            raise PipelineError(f"Stage '{stage.name}' already exists in pipeline")
        self.stages[stage.name] = stage
        return self

    def validate_and_plan(self) -> ExecutionPlan:
        """Validate the pipeline DAG and generate an execution plan.

        Returns:
            ExecutionPlan with topological stage ordering, costs, and artifacts.

        Raises:
            PipelineError: If any validation checks fail.
        """
        if not self.stages:
            # Empty pipeline is valid
            return ExecutionPlan()

        # Step 1: Collect all produced and required artifacts
        produced_artifacts: set[str] = set()
        required_artifacts: dict[str, list[str]] = {}  # artifact -> stages needing it

        for stage_name, stage in self.stages.items():
            for output in stage.outputs:
                produced_artifacts.add(output)
            for input_artifact in stage.inputs:
                if input_artifact not in required_artifacts:
                    required_artifacts[input_artifact] = []
                required_artifacts[input_artifact].append(stage_name)

        # Step 2: Check for missing inputs
        for artifact, stages in required_artifacts.items():
            if artifact not in produced_artifacts:
                raise PipelineError(
                    f"Artifact '{artifact}' required by {stages} is not produced by any stage"
                )

        # Step 3: Check for duplicate outputs
        output_producers: dict[str, str] = {}
        for stage_name, stage in self.stages.items():
            for output in stage.outputs:
                if output in output_producers:
                    raise PipelineError(
                        f"Artifact '{output}' produced by both '{output_producers[output]}' "
                        f"and '{stage_name}'"
                    )
                output_producers[output] = stage_name

        # Step 4: Topological sort with cycle detection
        order = self._topological_sort()
        if order is None:
            raise PipelineError(
                "Pipeline contains circular dependencies (cycle detected)"
            )

        # Step 5: Build execution plan
        plan = ExecutionPlan(
            stages=list(self.stages.values()),
            stage_order=order,
            artifact_producers=output_producers,
        )
        plan._stage_by_name = self.stages.copy()

        # Calculate total cost
        total_cost = sum(self.stages[name].cost_gpu_hours for name in order)
        plan.total_cost_gpu_hours = total_cost

        # Assign machines
        for stage_name in order:
            stage = self.stages[stage_name]
            plan.machine_assignments[stage_name] = stage.machine_required

        return plan

    def _topological_sort(self) -> list[str] | None:
        """Topological sort using DFS with cycle detection.

        Returns:
            List of stage names in topological order, or None if cycle exists.
        """
        # Build dependency graph: stage -> stages that must run before it
        deps: dict[str, set[str]] = {name: set() for name in self.stages}
        for stage_name, stage in self.stages.items():
            for input_artifact in stage.inputs:
                # Find the stage that produces this artifact
                for producer_name, producer in self.stages.items():
                    if input_artifact in producer.outputs:
                        deps[stage_name].add(producer_name)
                        break

        # DFS-based topological sort with cycle detection
        visited: dict[str, int] = {}  # 0: unvisited, 1: visiting, 2: visited
        order: list[str] = []

        def visit(node: str) -> bool:
            """DFS visit; return False if cycle detected."""
            if visited.get(node) == 1:
                # Back edge: cycle detected
                return False
            if visited.get(node) == 2:
                # Already processed
                return True

            visited[node] = 1
            # Visit dependencies first
            for dep in deps[node]:
                if not visit(dep):
                    return False
            visited[node] = 2
            # Append after all dependencies are visited (correct order)
            order.append(node)
            return True

        for stage_name in self.stages:
            if visited.get(stage_name, 0) == 0 and not visit(stage_name):
                return None

        # order is already in correct dependency order (no need to reverse)
        return order

    def describe(self) -> str:
        """Return a human-readable description of the pipeline.

        Useful for logging and debugging.
        """
        lines = [f"Pipeline: {self.name}"]
        lines.append(f"  Stages: {len(self.stages)}")
        for stage_name, stage in self.stages.items():
            lines.append(f"    {stage_name}: {stage.stage_type.value}")
            if stage.inputs:
                lines.append(f"      inputs: {', '.join(stage.inputs)}")
            if stage.outputs:
                lines.append(f"      outputs: {', '.join(stage.outputs)}")
        return "\n".join(lines)
